######################## default configuration ####################

baseURL = "https://www.michaelcontento.de/"
title = "Michael Contento"
theme = "bookworm-light"

defaultContentLanguage = "de"

# post pagination
paginate = "5"

# post excerpt
summaryLength = "20"

# google analytics
googleAnalytics = "" # example : UA-123-45

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# Modules ##############################

[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################

[imaging]
quality = "90"

############################# Outputs ##############################

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

############################## Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
#[[params.plugins.css]]
#link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

#################### default parameters ################################

[params]
logo = "images/logo.png"
logo_width = "80px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Michael Contento"
# contact form action
contact_form_action = "https://formspree.io/f/myyvjzzp" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Copyright &copy; Michael Contento"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = ""
access_token = ""

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

# cookies
[params.cookies]
enable = false
expire_days = 2

# Social Icons
[[params.social]]
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
url = "https://www.linkedin.com/in/michaelcontento"

[[params.social]]
icon = "lab la-xing" # https://icons8.com/line-awesome
url = "https://www.xing.com/profile/Michael_Contento"

[[params.social]]
icon = "lab la-github" # https://icons8.com/line-awesome
url = "https://github.com/MichaelContento"

[[params.social]]
icon = "las la-certificate" # https://icons8.com/line-awesome
url = "https://www.credly.com/users/michael-contento"

[[params.social]]
icon = "las la-bullhorn" # https://icons8.com/line-awesome
url = "https://sessionize.com/michaelcontento/"

[params.plausible]
enable = true
domain = "michaelcontento.de"

[params.giscus]
data_repo="michaelcontento/michaelcontento.github.io"
data_repo_id="R_kgDOIH1KxQ"
data_category="General"
data_category_id="DIC_kwDOIH1Kxc4CSE1h"
data_mapping="pathname"
data_strict="0"
data_reactions_enabled="1"
data_emit_metadata="0"
data_input_position="bottom"
data_theme="preferred_color_scheme"
data_lang=""
data_loading="lazy"
crossorigin="anonymous"
