[[main]]
name = "Start"
url = ""
weight = 10

# [[main]]
# name = "Über"
# url = "about/"
# weight = 20

[[main]]
name = "Blog"
url = "blog/"
weight = 30

[[main]]
name = "Kontakt"
url = "contact/"
weight = 40

############################# Footer Menu ########################

# [[footer]]
# name = "Privacy"
# url = "privacy/"
# weight = 10

# [[footer]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 20