#################### default parameters ################################
# favicon
favicon = "images/favicon.png"

# logo
#logo = "images/logo.png"
#logo_dark = "images/logo-w.png"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "100px"

# logo text will only show when logo is missing.
logo_text = "Boilerplate"

# navbar fixed to top
navbar_fixed = false

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# contact form action
contact_form_action = "https://formspree.io/f/myyvjzzp" # contact form works with https://formspree.io

# search
search = true

# Sidebar
sidebar = "false" # sidebar value (true or false)

# copyright
theme_copyright = false
copyright = "&copy; Copyright by Michael Contento"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
mainSections = ["blog"]

# theme mode
theme_switch = true
default_mode = "light" # available options [light/dark]

popular_posts = false

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.


# Instagram feed
[instafeed]
enable = false
access_token = ""

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code


# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
#sidebar = ["search", "categories",  "recent-post", "social"]

############################# social site ########################
[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/michaelcontento"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/michaelcontento/"

[[social]]
title = "Xing"
icon = "fab fa-xing" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.xing.com/profile/Michael_Contento"

[[social]]
title = "NPM"
icon = "fab fa-npm" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.npmjs.com/~michaelcontento"