title = "Michael Contento"
baseURL = "https://www.michaelcontento.de/"

# Option 1 (recommended): adding the theme as a Hugo module
# theme = "github.com/Lednerb/bilberry-hugo-theme/v3"

# Option 2: cloning/copying the theme files
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "de"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Michael Contento"
  description = "Bilberry Premium Theme for Hugo."
  keywords = "blog,personal,software development,c#,azure,.net"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "MS0H7HCJLY"
  algolia_apiKey    = "8c99c23855125addf5ee267c0e80d00d"
  algolia_indexName = "www_michaelcontento_de"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # Enable / Disable comments on the articles via commento
  # commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  umami_website_id = "6992b71c-5c7f-465f-af26-5b3ce06e274c"

  # Enable / Disable Giscus comments
  giscus             = true
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "michaelcontento/michaelcontento.github.io"
  giscusRepositoryId = "R_kgDOIH1KxQ"
  giscusMapping      = "pathname"
  giscusCategory     = "General"
  giscusCategoryId   = "DIC_kwDOIH1Kxc4CSE1h"
  giscusTheme        = "preferred_color_scheme" # light
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "en"
  giscusCrossOrigin  = "anonymous"

  # Enable / Disable Utterances comments
  utterances            = false
  utterancesJsUrl       = "https://utteranc.es/client.js"
  utterancesRepository  = "[ENTER REPO HERE]"
  utterancesIssueTerm   = "pathname"
  utterancesLabel       = "Comment"
  utterancesTheme       = "github-light"
  utterancesCrossOrigin = "anonymous"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = ""

    # if you want to use libravatar or gravatar for the header image
    avatarEmail = "mail@michaelcontento.de"

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = ""

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = true

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/article/installing-bilberry-theme/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatic localization of the article's PublishedDate with momentjs
    enableMomentJs = false

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://www.linkedin.com/in/michaelcontento", icon = "fab fa-linkedin-in", rel = "me" },
      { link = "https://www.xing.com/profile/Michael_Contento", icon = "fab fa-xing" },
      { link = "https://github.com/MichaelContento", icon = "fab fa-github" },
      { link = "https://www.credly.com/users/michael-contento", icon = "fas fa-award" },
      { link = "https://sessionize.com/michaelcontento", icon = "fas fa-bullhorn" },
    ]

    # show an archive link in the footer
    showArchive = true

    # archive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006"

    # credits line configuration
    copyrightBy = "by Michael Contento"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/michaelcontento/michaelcontento.github.io"
    creditsText = "Impressum"
    creditsUrl = "/page/imprint"

[permalinks]
article = "/article/:year/:month/:day/:title/"

# customize your available languages for your multi-lingual site
# or delete one of the [Languages.xx] blocks to use the theme with only one supported language
[Languages]
  [Languages.de]
    weight = 10
    subtitle = "Softwareentwickler | Azure-Cloud-Ninja | Imker | Dad"
  [Languages.en]
    weight = 20
    subtitle = "Softwaredeveloper | Azure-Cloud-Ninja | Beekeeper | Dad"
    creditsText = "Imprint"
    creditsUrl = "/en/page/imprint"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true

  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

# do NOT change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
