name: Import Credly badges

on:
  schedule: 
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import credly badges
        uses: michaelcontento/credly2hugo-action@v1
        with: 
          username: michael-contento

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "credly2hugo: Imported new files from Credly"
