name: Import Credly badges

on:
  schedule: 
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Import credly badges
        uses: michaelcontento/credly2hugo-action@main
        with: 
          username: michael-contento

      - name: Commit new badges (if changed)
        run: |
          git config --global user.name 'Michael Contento'
          git config --global user.email 'michaelcontento@users.noreply.github.com'
          git add .         
          if ! git diff-index --quiet HEAD; then
            git commit --message 'credly2hugo: Updated creadly badges data file'
            git push origin main
          fi
