name: Deploy GitHub Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
            hugo \
                --minify \
                --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Upload Data
        if: github.ref == 'refs/heads/main'
        working-directory: ./algolia
        run: |
          npm install
          npm run data-upload -- \
            -c \
            -f ../public/index.json \
            -a ${{ vars.ALGOLIA_APP_ID }} \
            -k ${{ secrets.ALGOLIA_ADMIN_API_KEY }} \
            -n ${{ vars.ALGOLIA_INDEX_NAME }}
          npm run data-upload -- \
            -f ../public/en/index.json \
            -a ${{ vars.ALGOLIA_APP_ID }} \
            -k ${{ secrets.ALGOLIA_ADMIN_API_KEY }} \
            -n ${{ vars.ALGOLIA_INDEX_NAME }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v1
